spring:
  datasource:
    url: jdbc:mysql://localhost:3306/systemReview
    username: root
    password: Pir**z1379
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

    show-sql: true
logging:
  level:
    com:
      example:
        studentserviceapplication: DEBUG
    root: info

server:
  port: 8081